FROM apache/airflow:2.10.4

# libgomp1 requerido por LightGBM (OpenMP)
USER root
RUN apt-get update && apt-get install -y --no-install-recommends libgomp1 && rm -rf /var/lib/apt/lists/*
USER airflow

# Instalar dependencias de ML en el entorno de Airflow
COPY requirements-ml.txt /requirements-ml.txt
RUN pip install --no-cache-dir -r /requirements-ml.txt