server {
    listen 8080;
    server_name localhost;

    # Página principal
    location / {
        # La magia ocurre aquí: antes de servir, consulta al WAF
        auth_request /waf_check;
        
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }

    # Endpoint interno para conectarse con FastAPI
    location = /waf_check {
        internal;
        # host.docker.internal es la IP del host de Mac dentro de Docker
        proxy_pass http://host.docker.internal:5083/predict/nginx;
        
        # NGINX no manda el body en auth_request por defecto, pero nosotros
        # extraemos las features basándonos puramente en la URI y el Method
        proxy_pass_request_body off;
        proxy_set_header Content-Length "";
        
        # Headers mágicos: le pasamos la URI y Método originales a la API
        proxy_set_header X-Original-URI $request_uri;
        proxy_set_header X-Original-Method $request_method;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Custom Error Page para mostrar un bloqueo elegante
    error_page 403 /403.html;
    location = /403.html {
        charset utf-8;
        return 403 "<html><head><meta charset='UTF-8'><title>403 Forbidden</title></head><body style='background-color:#111; color:red; text-align:center; padding-top:100px; font-family:sans-serif;'><h1>🛑 ACCESO BLOQUEADO POR AI WAF 🛑</h1><p>Tu petición ha sido clasificada como anómala o maliciosa con alta confianza.</p></body></html>";
    }
}
